# ?????
server.port=8080

spring.application.name=finance-manager-java

# JSP???????
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


# ?????URL?finance_db??????????????
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
# ??????????root?
spring.datasource.username=root
# ?????
spring.datasource.password=rct122424
# ???????Spring Boot 3.x ???????????????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Hibernate) ???????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ??WebJars
spring.web.resources.add-mappings=true

# ====== ?????SQL??? ======
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# ???????CSS, JS??
spring.web.resources.static-locations=classpath:/static/

# ??????SQL????????
spring.jpa.show-sql=true

# ????????? WARN???????????????INFO???
logging.level.root=WARN

# ????????
server.error.include-stacktrace=always
server.error.include-message=always

# ??JSP????
server.jsp-servlet.init-parameters.development=true

# ??????
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# JSP??
spring.mvc.locale=zh_CN
spring.mvc.locale-resolver=fixed